### ISSUE TITLE
Indicator and Criteria Table visualisation

### ISSUE THREAD

**Issue by mscholl** [crismaproject/worldstate-analysis-widgets#1]
This issue describes the Indicator Table Visualisation widget. The indicators of selected worldstates shall be displayed in a table as shown in the following image:

![screen shot 2014-02-13 at 17 52 13](https://f.cloud.github.com/assets/973421/2162177/4691852c-94cf-11e3-916b-ba580eb05936.png)

The indicators may or may not be grouped. However, in any case the table displays a column containing all the indicators. The groups are optional. Additionally the table provides a column for every selected worldstate which contains the values (and units) of the corresponding indicator. The name of the column is the worldstate name.

An AngularJS directive shall be used to implement this feature. This directive's interface shall be an array of selected worldstates.

The general format if the indicator/criteria vector can be found here. 
https://github.com/crismaproject/worldstate-analysis-widgets/wiki/Indicator-Criteria-vector-format

**Comment by dameiers** [comment]
closed via a0ca91d88d7e1034fc3c5281e66c5a44487f7284
