### ISSUE TITLE
Indicator and Criteria Relation Analysis Graph Visualisation

### ISSUE THREAD

**Issue by mscholl** [crismaproject/worldstate-analysis-widgets#2]
This issue describes the Indicator and Criteria Relation Analysis Graph Visualisation widget. The indicators/criteria of selected worldstates shall be displayed in a graph as shown in the following image:

TODO

All available indicators/criteria shall be listed twice. One list shall be used for the selection of the x-axis and the other for the selection of the y-axis. As soon as the user has selecte a single entry in each list a graph visualisation (scatter plot) shall be shown. The values are taken from the indicator/criteria sets of every selected worldstate.

An AngularJS directive shall be used to implement this feature. This directive's interface shall be an array of selected worldstates.

The general format if the indicator/criteria vector can be found here.
https://github.com/crismaproject/worldstate-analysis-widgets/wiki/Indicator-Criteria-vector-format

**Comment by dameiers** [comment]
closed via 190750612558cfdd3e50be451ec63ef10d01426c
