### ISSUE TITLE
file choosers  works only the first time using FireFox

### ISSUE THREAD

**Issue by dameiers** [crismaproject/worldstate-analysis-widgets#64]
when adding indicator files, criteria functions or decision strategy files,  this only works the first time. After that the file chooser opens, but the selected file / files   is / are not added.

**Comment by p-a-s-c-a-l** [comment]
Fixed in https://github.com/clarity-h2020/scenario-analysis/commit/f6a92f547f4bc563b0beb41c17c6ef35f9914748.
